name: Java CI

on: [push]

jobs:
  build-microprofile-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: t1/microprofile-sandbox
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
    - name: mvn build
      run: |
        cd proposals/problem-details
        mvn --batch-mode install
    - uses: actions/upload-artifact@v1
      with:
        name: mp-problemdetails
        path: /home/runner/.m2/repository/io/microprofile/sandbox/

  build:
    strategy:
      matrix:
        container:
        - wildfly
        #- payara
        #- open-liberty:19.0.0.9-javaee8-java11
        #- tomee # TODO TomEE enable when fixed https://github.com/t1/problem-details/issues/17
        jdk: [8, 11]

    runs-on: ubuntu-latest
    needs: build-microprofile-artifacts
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
    - uses: actions/download-artifact@v1
      with:
        name: mp-problemdetails
        path: /home/runner/.m2/repository/io/microprofile/sandbox/
    - name: Pre-fetch slf4j dependencies # required by jee-testcontainers
      run: |
        mvn --batch-mode dependency:get -Dartifact=org.slf4j:slf4j-api:1.7.30:jar
        mvn --batch-mode dependency:get -Dartifact=org.slf4j:slf4j-jdk14:1.7.30:jar
    - name: Build with Maven
      run: mvn --batch-mode install -Djee-testcontainer=${{ matrix.container }}
